### ISSUE TITLE
prisma & vulcan-next

### ISSUE THREAD

**Issue by j209** [VulcanJS/vulcan-next#141]
Hi
[Prisma](https://www.prisma.io/) [now supports mongodb](https://www.prisma.io/docs/concepts/database-connectors/mongodb).
can vulcan-next integrate with prisma?

**Comment by eric-burel** [comment]
Hi, 


Short answer: yes you can and it will work as expected, but we won't embed Prisma out-of-the-box (except if we find an easy, optional way to do so in the future)

Long answer :
- It can already integrate as long as you create a Prisma connector in [Vulcan NPM](https://github.com/VulcanJS/vulcan-npm), like the one we have for Mongo: https://github.com/VulcanJS/vulcan-npm/blob/main/packages/mongo/connector.ts
The connector define basic CRUD operations against the database, that are then used by Vulcan GraphQL layer to get data.
It would be very easy and I would gladly accept a PR introducing a "vulcan-prisma" package that does this.

Then, you can install Prisma in Vulcan Next and use this connector in your models.

- It adds a huge, complex layer to the application, that's why I am not really eager to integrate it out-of-the-box in Vulcan Next starter, even though it has been discussed (and Prisma even sponsored us).
Vulcan differs from a framework like [Blitz.js](https://blitzjs.com/) in this respect, we prefer simple, direct and opinionated choices, that are more suited for junior developers and also easier to maintain in the long run. 
However I would be ok to add something like a recipe system that automatically install Prisma for you, but I wouldn't maintain something like this officially, that's too much work for the value added.
