### ISSUE TITLE
vulcan-next vs other fullstack react frameworks

### ISSUE THREAD

**Issue by j209** [VulcanJS/vulcan-next#159]
Vulcan next, Blitz, and Redwood were all created in 2020. Why vulcan is less popular and used than others?
Blitz more than 11000 stars
Redwood more than 12000 stars
and vulcan-next 300 stars!!

**Comment by eric-burel** [comment]
Hi,

Very interesting question!

Vulcan is actually older than that, it dates from 2016 (and is based on the even older framework Telescope which dates back from 2012). 

This old [Meteor version of Vulcan](https://github.com/VulcanJS/Vulcan) has 8k stars on GitHub and used to be very popular. It still powers a few apps such as the State of JS/CSS survey form. Vulcan was to Meteor what Blitz is for Next. 
Vulcan Meteor however lost a lot users and popularity because Meteor itself, while being extremely powerful and innovative, had a lot of unaddressed technical issues and a very strong lock-in. Meteor was bought late 2019 and development started to be active again but we had already moved on by then.


Vulcan Next is a rewrite of Vulcan for a more modern JS ecosystem. Next is our first-class citizen, but we immediately adopted a toolkit approach, so we now also propose an Express starter and we work on a [Remix starter](https://github.com/VulcanJS/vulcan-remix). Blitz only started to pivot to a toolkit only early 2022 and Redwood is not a toolkit therefore not really meant to be reused outside of Redwood apps.



Vulcan is a "brownfield" project, while Redwood and Blitz are "greenfield". Starting from scratch makes you faster and they reached maturity earlier than us. 

Redwood is backed by a big name, Tom Preston-Werner, co-founder of GitHub, so it had an immediate popularity boost.
The comparison to Blitz is more interesting. Being greenfield, they had a very lean approach, producing a MVP quickly, building a community and then iterating.  
However at Vulcan, we first needed a very costly cleanup step of the existing codebase. It's difficult to involve contributors during this stage, so we couldn't have a "lean" approach. 


We can now consider this cleanup work to be done.  Being a "survivor" of the 2010-2020 JavaScript era, we cumulate a lot of knowledge and we are now way more confident in our choices. Contrary to Redwood or Blitz, our architectural choices implies that we don't require much maintenance or funding, which I consider to be a strategical advantage. Our history makes us aware that frameworks may have popularity variations overtime, and that a good framework needs to be maintainable by a limited number of contributors to resist those variations.


We managed to create a state of the art monorepo, [Vulcan NPM](https://github.com/VulcanJS/vulcan-npm) that makes development really efficient and pleasurable.

We have been focusing on communication and community building only for a few weeks now, hence the popularity gap. But I am very confident that Vulcan can play a significant role in the JS ecosystem in the months to come :)

**Comment by j209** [comment]
Thank you very much for your prompt and complete reply.
another problem:
Unlike the previous two frameworks, there is no instructional video about Vulcan Next on YouTube

**Comment by eric-burel** [comment]
Yes good remark as well, earlier this year I've been teaching myself how to use OBS, I've filmed an entire web development course for my students and invested in a relatively correct mic and webcam to make proper videos.
Expect Vulcan tutorials in a few months maximum. In the meantime, I've created an interative tutorial that I will keep up to date: https://vulcan-next.vercel.app/learn

**Comment by stigfaerch** [comment]
@eric-burel how does one join on Discord?

**Comment by eric-burel** [comment]
Hi @stigfaerch you can join the vulcan channel on GraphQL discord: https://discord.com/channels/625400653321076807/974584105167618049
I am also hanging on Next.js Discord
